name: build sing-box-subscribe

on:
    # 手动触发
    workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v1.8.0
        with:
          #设置两个secrets: docker的用户名和密码
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: 编译上传docker image
        uses: docker/build-push-action@v2.4.0
        with:
          #Dockerfile的目录
          context: ./
          #编译的目标系统，为了方便玩客云，所以我编译了 arm/v7,amd64
          platforms: linux/arm64,amd64
          push: true
            #docker提交的名字
          tags: "sztuxp/sing-box-subscribe:1.0.0,sztuxp/sing-box-subscribe:latest"标签：“
